version: "3.9"
services:
  nginx:
    restart: always
    image: nginx:latest
    network_mode: "host"
    #    ports:
    #      - "80:80"
    volumes:
      - ./data/nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./client/dist:/var/www/index:ro

#  server:
#    restart: always
#    ports:
#      - "2022:2022"
#    build:
#      context: server